In [40]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('../../data_files/Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values



In [5]:
dataset.shape

(10000, 14)

In [18]:
y = dataset.iloc[:, 13].values


In [19]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [7]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [8]:
# ------ Part-1: Data preprocessing ----------
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder,StandardScaler
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])



In [10]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [11]:
s = StandardScaler()

In [12]:
X1 = s.fit_transform(X)

In [14]:
X1

array([[-0.32622142, -0.90188624, -1.09598752, ...,  0.64609167,
         0.97024255,  0.02188649],
       [-0.44003595,  1.51506738, -1.09598752, ..., -1.54776799,
         0.97024255,  0.21653375],
       [-1.53679418, -0.90188624, -1.09598752, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.60498839, -0.90188624, -1.09598752, ..., -1.54776799,
         0.97024255, -1.00864308],
       [ 1.25683526,  0.30659057,  0.91241915, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 1.46377078, -0.90188624, -1.09598752, ...,  0.64609167,
        -1.03067011, -1.07636976]])

In [38]:
y

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [1., 0.]], dtype=float32)

In [41]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X1, y, test_size=0.3, random_state=0)


In [16]:
import keras

Using TensorFlow backend.


In [17]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [18]:
y=keras.utils.to_categorical(y)

In [19]:
y

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [1., 0.]], dtype=float32)

(10000, 2)

In [21]:
X_train.shape

(7000, 10)

In [ ]:
X

In [42]:
# # Feature Scaling
# from sklearn.preprocessing import StandardScaler
# sc_X = StandardScaler()
# X_train = sc_X.fit_transform(X_train)
# X_test = sc_X.transform(X_test)

# ------- Part-2: Build the ANN --------

# import keras library and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

# Initializing the ANN
classifier = Sequential()
# Adding the input layer and the first hidden layer
ip_layer = Dense(activation='relu', input_dim=10, kernel_initializer='uniform', units=10)
classifier.add(ip_layer)

# Adding first hidden layer
layer_info = Dense(activation='relu', kernel_initializer='uniform', units=1000)
classifier.add(layer_info)

layer_info = Dense(activation='relu', kernel_initializer='uniform', units=500)
classifier.add(layer_info)


layer_info = Dense(activation='relu', kernel_initializer='uniform', units=250)
classifier.add(layer_info)

layer_info = Dense(activation='relu', kernel_initializer='uniform', units=100)
classifier.add(layer_info)

# Adding output layer
layer_info = Dense(activation='sigmoid', kernel_initializer='uniform', units=1)
classifier.add(layer_info)

# Compiling the ANN
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])



Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [43]:
classifier.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_8 (Dense)              (None, 1000)              11000     
_________________________________________________________________
dense_9 (Dense)              (None, 500)               500500    
_________________________________________________________________
dense_10 (Dense)             (None, 250)               125250    
_________________________________________________________________
dense_11 (Dense)             (None, 100)               25100     
_________________________________________________________________
dense_12 (Dense)             (None, 1)                 101       
Total params: 662,061
Trainable params: 662,061
Non-trainable params: 0
________________________________________________

In [45]:
# Fitting the ANN to the training set
classifier.fit(X_train, y_train, batch_size=100, epochs=25)

Epoch 1/25
7000/7000 [==============================] - 1s 165us/step - loss: 0.3337 - accuracy: 0.8660
Epoch 2/25
7000/7000 [==============================] - 1s 181us/step - loss: 0.3323 - accuracy: 0.8659
Epoch 3/25
7000/7000 [==============================] - 1s 182us/step - loss: 0.3306 - accuracy: 0.8656
Epoch 4/25
7000/7000 [==============================] - 1s 193us/step - loss: 0.3298 - accuracy: 0.8656
Epoch 5/25
7000/7000 [==============================] - 1s 212us/step - loss: 0.3284 - accuracy: 0.86590s - loss: 0.3277 - ac
Epoch 6/25
7000/7000 [==============================] - 2s 219us/step - loss: 0.3293 - accuracy: 0.8661
Epoch 7/25
7000/7000 [==============================] - 1s 189us/step - loss: 0.3275 - accuracy: 0.86670s -
Epoch 8/25
7000/7000 [==============================] - 1s 180us/step - loss: 0.3269 - accuracy: 0.8689
Epoch 9/25
7000/7000 [==============================] - 1s 177us/step - loss: 0.3278 - accuracy: 0.8684
Epoch 10/25
7000/7000 [===============

In [46]:
y_pred=classifier.predict(X_test)

In [52]:
y

[0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [51]:
y=[]
for i in range(len(y_pred)):
    if y_pred[i]< 0.5:
        y.append(0)
    else:
        y.append(1)
    

In [33]:
y_pred=[np.argmax(x) for x in y_pred]

In [36]:
y_test = [np.argmax(x) for x in y_test]

In [37]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8566666666666667

In [34]:

# Predicting the Test set results
y_pred = classifier.predict(X_test)


In [35]:
y_pred

array([[0.7028462 , 0.29715383],
       [0.6596611 , 0.3403389 ],
       [0.8055333 , 0.19446668],
       ...,
       [0.89954144, 0.10045855],
       [0.9691766 , 0.03082346],
       [0.18028161, 0.8197184 ]], dtype=float32)

In [54]:
y=[]
for i in range(len(y_pred)):
    y.append(np.argmax(y_pred[i]))
    

In [38]:
[np.argmax(x) for x in y_test ]

[0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,


In [55]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y)

0.793

# 