# Learn Keras for Deep Neural Networks
## Chapter 1 - An Introduction to Deep Learning and Keras


In [ ]:
# keras: python deep learning framework built on top of TF(tensor flow).

#   https://en.wikipedia.org/wiki/Keras --Link for keras(source:wikipedia)

# Notes on keras:
# Keras is an open-source neural-network library written in Python. 
It is capable of running on top of TensorFlow, Microsoft Cognitive Toolkit, R, Theano, or PlaidML.[1][2] Designed to enable fast experimentation with deep neural networks, it focuses on being user-friendly, modular, and extensible. It was developed as part of the research effort of project ONEIROS (Open-ended Neuro-Electronic Intelligent Robot Operating System),[3] and its primary author and maintainer is François Chollet, a Google engineer.
Chollet also is the author of the XCeption deep neural network model

->Keras contains numerous implementations of commonly used neural-network building blocks such as layers, objectives, activation functions, optimizers, and a host of tools to make working with image and text data easier to simplify the coding necessary for writing Deep Neural Network code.

->In addition to standard neural networks, Keras has support for convolutional and recurrent neural networks. It supports other common utility layers like dropout, batch normalization, and pooling.[9]

Keras allows users to productize deep models on smartphones (iOS and Android), on the web, or on the Java Virtual Machine.[10] It also allows use of distributed training of deep-learning models on clusters of Graphics Processing Units (GPU) and Tensor processing units (TPU) principally in conjunction with CUDA.[11]

In [ ]:
# tensorflow: python deep learning framework .

#notes on tensor flow:
TensorFlow is a free and open-source software library for dataflow and differentiable programming across a range of tasks. 
It is a symbolic math library, and is also used for machine learning applications such as neural networks.[4] 
It is used for both research and production at Google

TensorFlow was developed by the Google Brain team for internal Google use. It was released under the Apache License 2.0 on November 9, 2015.

In [1]:
!pip install keras

In [2]:
!pip install tensorflow

A sneak peek in the Keras Framework

In [6]:
#Import required packages
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

In [7]:
np.random.seed(2018)
train_data, test_data = np.random.random((1000, 3)), np.random.random((500, 3))
#Generate dummy results for 1000 students : Whether Passed (1) or Failed (0)
labels = np.random.randint(5, size=(1000, 1))   #generates 0,1,2,3 and 4 randomly with 1000 samples and one column

In [9]:
train_data

array([[0.88234931, 0.10432774, 0.90700933],
       [0.3063989 , 0.44640887, 0.58998539],
       [0.8371111 , 0.69780061, 0.80280284],
       ...,
       [0.76474832, 0.12224649, 0.06019634],
       [0.21847107, 0.57064847, 0.27701246],
       [0.97785211, 0.81210972, 0.34780075]])

In [11]:
np.random.randint(5, size=(2, 4))   #learning

array([[4, 1, 3, 3],
       [1, 1, 0, 1]])

In [10]:
labels

array([[4],
       [4],
       [1],
       [4],
       [0],
       [2],
       [0],
       [2],
       [1],
       [4],
       [3],
       [0],
       [3],
       [3],
       [4],
       [4],
       [4],
       [3],
       [4],
       [2],
       [1],
       [2],
       [4],
       [3],
       [4],
       [3],
       [4],
       [1],
       [3],
       [2],
       [2],
       [1],
       [4],
       [0],
       [1],
       [3],
       [2],
       [0],
       [0],
       [0],
       [3],
       [0],
       [0],
       [1],
       [1],
       [0],
       [2],
       [4],
       [2],
       [1],
       [3],
       [2],
       [4],
       [4],
       [1],
       [2],
       [4],
       [3],
       [3],
       [0],
       [1],
       [3],
       [3],
       [3],
       [1],
       [0],
       [3],
       [4],
       [0],
       [1],
       [4],
       [0],
       [0],
       [2],
       [3],
       [2],
       [4],
       [0],
       [3],
       [4],
       [4],
       [4],
       [3],
    

In [12]:
np.random.random((9,2))


array([[0.56483978, 0.38110148],
       [0.80550362, 0.56157338],
       [0.01302482, 0.54218983],
       [0.6005349 , 0.11518427],
       [0.48182455, 0.30980366],
       [0.40938373, 0.61209506],
       [0.68175335, 0.53679221],
       [0.5975519 , 0.44051974],
       [0.60974298, 0.85996287]])

In [121]:
np.random.randn(2)

array([-0.27125813, -1.45463451])

In [93]:
a=np.random.seed(10)
a

In [40]:
train_data

array([[0.88234931, 0.10432774, 0.90700933],
       [0.3063989 , 0.44640887, 0.58998539],
       [0.8371111 , 0.69780061, 0.80280284],
       ...,
       [0.76474832, 0.12224649, 0.06019634],
       [0.21847107, 0.57064847, 0.27701246],
       [0.97785211, 0.81210972, 0.34780075]])

In [12]:
train_data.shape

(1000, 3)

In [21]:
labels.shape

(1000, 1)

In [16]:
#Defining the model structure with the required layers, # of neurons, activation function and optimizers
model = Sequential()  # sequential container initialized.
model.add(Dense(10, input_dim=3, activation='relu'))  #HIDDEN LAYER 1  #here 10 is the count of neurons and 3 is the size/number of inputs
model.add(Dense(5, activation='relu'))  #HIDDEN LAYER 2



model.add(Dense(1, activation='sigmoid'))  # OUTPUT LAYER    #sigmid function is applied:e^x / 1+e^-x  #model.add(): Adds a layer instance on top of the layer stack.


model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])   #model.compile(): Configures the model for training.



In [18]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 10)                40        
_________________________________________________________________
dense_5 (Dense)              (None, 5)                 55        
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 6         
Total params: 101
Trainable params: 101
Non-trainable params: 0
_________________________________________________________________


In [25]:
train_data.shape

(1000, 3)

In [21]:
#Train the model and make predictions
model.fit(train_data, labels, epochs=15,batch_size=32)


# batchsize and epochs: https://www.quora.com/What-is-the-difference-between-iterations-and-epochs-in-Convolution-neural-networks
#Epoch : It simply represents one iteration over the entire dataset
#Batches : We split the total data into many segments or Batches
#Iterations : Iterations are number of batches we need to compile one Epoch

Epoch 1/15
1000/1000 [==============================] - 0s 82us/step - loss: -2.5972 - accuracy: 0.1960
Epoch 2/15
1000/1000 [==============================] - 0s 109us/step - loss: -3.8068 - accuracy: 0.1960
Epoch 3/15
1000/1000 [==============================] - 0s 104us/step - loss: -5.2775 - accuracy: 0.1960
Epoch 4/15
1000/1000 [==============================] - 0s 98us/step - loss: -7.0926 - accuracy: 0.1960
Epoch 5/15
1000/1000 [==============================] - 0s 88us/step - loss: -9.3016 - accuracy: 0.1960
Epoch 6/15
1000/1000 [==============================] - 0s 102us/step - loss: -12.0763 - accuracy: 0.1960
Epoch 7/15
1000/1000 [==============================] - 0s 91us/step - loss: -15.3769 - accuracy: 0.1960
Epoch 8/15
1000/1000 [==============================] - 0s 119us/step - loss: -19.3997 - accuracy: 0.1960
Epoch 9/15
1000/1000 [==============================] - 0s 98us/step - loss: -24.2197 - accuracy: 0.1960
Epoch 10/15
1000/1000 [==============================] -

In [12]:
#Make predictions from the trained model
predictions = model.predict(test_data)
predictions

array([[0.9953595 ],
       [0.9987051 ],
       [0.99792886],
       [0.99627024],
       [0.9970968 ],
       [0.98909295],
       [0.9980233 ],
       [0.9959101 ],
       [0.9964551 ],
       [0.99052334],
       [0.99643886],
       [0.9991925 ],
       [0.99930036],
       [0.99876153],
       [0.99654305],
       [0.99776095],
       [0.99918556],
       [0.9971235 ],
       [0.99902844],
       [0.9992951 ],
       [0.99816024],
       [0.9969245 ],
       [0.99348265],
       [0.99576926],
       [0.99174964],
       [0.99512064],
       [0.99724984],
       [0.993144  ],
       [0.99925196],
       [0.99854845],
       [0.99624425],
       [0.99645805],
       [0.9953455 ],
       [0.99821806],
       [0.99718904],
       [0.99508727],
       [0.99916637],
       [0.9982121 ],
       [0.9959763 ],
       [0.9926169 ],
       [0.9996345 ],
       [0.9994342 ],
       [0.999683  ],
       [0.99848324],
       [0.99873674],
       [0.9949044 ],
       [0.9987017 ],
       [0.998

In [ ]:
#